### PR TITLE
Allow additional configuration of DbContextMock

### PR DESCRIPTION
**Pull request by nevaldas**
This PR solves my issue #39. It allows me to pass in my own configuration, which does not use the Object. 
P.S. In 90% of cases it would be enough to use `Of<DbContext>` as argument for DatabaseFacade's constructor. But I didn't want to impact original solution. By default, this will work as it worked, there is no impact for others as this just adds additional possibilities.

### CODE REVIEW

**Comment by nevaldas** [comment]
Any idea when this could be completed, @huysentruitw?

**Comment by huysentruitw** [comment]
Hi, thanks for this PR. 

I don't think this code compiles (and I can't seem to trigger GitHub actions manually for some reason).

May I ask if you can first add a unit-test that demonstrates the issue with the original DbContextMock. That way I can easily reproduce the issue at my end as it feels like the changes in this PR make things a bit too complex for a "niche problem" and I would like to find an easier solution.

**Comment by nevaldas** [comment]
I have added two unit tests. One is using original flow (using that ConfigureTransaction thing, which calls Object property and voids any .As<T> setups), another one is using my configuration property. The code compiles on my side. I'm using VS2022 Enterprise.  

There is a easier solution:
Instead of `var mockDbFacade = new Mock<DatabaseFacade>(context.Object);` we could do `var mockDbFacade = new Mock<DatabaseFacade>(Mock.Of<DbContext>);`. And it would work fine for majority of people, but there are cases when it would not, so why limit people and fix only my problem, if we can open additional possibilities for others, without introducing any issues? Let's be open for modifications.

**Comment by huysentruitw** [comment]
I have created a different PR that should also allow you to post-configure the DbContextMock without complicating the public API of this library. Please see of https://github.com/cup-of-tea-dot-be/entity-framework-core-mock/pull/43 would suit your needs.

**Pull request closed without merging**
